### ISSUE TITLE
PHP Unit Test Fails with, get_users_in_context() is bugged

### ISSUE THREAD

**Issue by andrewnormore** [elearningsoftware/moodle-mod_journal#100]
This function seems to be broken, it has been updated to select j.userid which there is no column on journal for userid. I have pasted the solution below and will do a pull request to fix it.

`    public static function get_users_in_context(userlist $userlist) {
        $context = $userlist->get_context();

        if (!is_a($context, \context_module::class)) {
            return;
        }

        // Find users with journal entries.
        $sql = "
            SELECT j.userid
              FROM {journal} j
              JOIN {modules} m
                ON m.name = :journal
              JOIN {course_modules} cm
                ON cm.instance = j.id
               AND cm.module = m.id
              JOIN {context} ctx
                ON ctx.instanceid = cm.id
               AND ctx.contextlevel = :modulelevel
             WHERE ctx.id = :contextid";
        $params = ['journal' => 'journal', 'modulelevel' => CONTEXT_MODULE, 'contextid' => $context->id];

        $userlist->add_from_sql('userid', $sql, $params);
    }`

SOLUTION: 
`public static function get_users_in_context(userlist $userlist) {
        $context = $userlist->get_context();

        if (!is_a($context, \context_module::class)) {
            return;
        }

        // Find users with journal entries.
        $sql = "
                SELECT je.userid
                    FROM {journal_entries} je
                    JOIN {modules} m
                        ON m.name = :journal
                    JOIN {course_modules} cm
                        ON cm.instance = je.id
                    AND cm.module = m.id
                    JOIN {context} ctx
                        ON ctx.instanceid = cm.id
                    AND ctx.contextlevel = :modulelevel
                    WHERE ctx.id = :contextid";
        $params = ['journal' => 'journal', 'modulelevel' => CONTEXT_MODULE, 'contextid' => $context->id];

        $userlist->add_from_sql('userid', $sql, $params);
    }`

**Comment by larsbonczek** [comment]
This was fixed in #101

**Comment by adrian-sarmas** [comment]
I'll close this since it was fixed in the pull request.
