### ISSUE TITLE
Performance issue with upgrade

### ISSUE THREAD

**Issue by grillonbleu** [elearningsoftware/moodle-mod_journal#111]
Hi,

The upgrade step for mod_journal instances installed prior to `2022041100` updates unmarked journal entries by executing N database queries, where N = the amount of concerned entries. For a busy Moodle instance, this can be a lot (for us it made ~40,000 MySQL queries, which was unexpected for a plugin update). This operation can be made in a single query if we use `$DB->set_field_select`.

I’ll open a PR with a fix shortly.

**Comment by adrian-sarmas** [comment]
Thank you @grillonbleu for contributing! I've merged the PR.
