### ISSUE TITLE
Journal entries do not show in recent activity block

### ISSUE THREAD

**Issue by drachels** [elearningsoftware/moodle-mod_journal#20]
It appears the lib.php function code for showing recent activity by students in the Recent Activity block has never been updated to work with the new logging system. Moodle 2.6 and lower it works. Moodle 2.7 through 3.1 it doesn't provide any results except when you add a Journal activity.

**Comment by drachels** [comment]
I have a partially working fix. The link in the block to take you to the activity is not getting the right id yet, and I need to format the entry to get rid of extra blank lines.

**Comment by drachels** [comment]
I have refined my fix so that it works fine for admin and teacher and the links take them to the report.php page so they can start grading. Need to put in a switch for students so they go to view.php instead of report.php so they can view or edit only their entry. Right now, them going to report.php gives them an error, as it should.

**Comment by drachels** [comment]
My changes and now in my master branch at https://github.com/dmonllao/moodle-mod_journal
I have initiated a pull request. Hope I did everything correctly.

**Comment by adrian-sarmas** [comment]
This issue has been closed. See https://github.com/elearningsoftware/moodle-mod_journal/pull/21 for the details.
