### ISSUE TITLE
Security improvements - should make better use of DML params

### ISSUE THREAD

**Issue by danmarsden** [elearningsoftware/moodle-mod_journal#25]
a lot of the functions in lib.php pass parameters into in-line SQL - $currentgroup, $cutofftime, $journalid - tracing these functions doesn't suggest any easy SQL injections, but the fact I have to go looking through the code makes it hard to security review this plugin. it would be really good to get this fixed and use parameters instead of passing in-line.

**Comment by adrian-sarmas** [comment]
This has been fixed in other commits and is no longer an issue.
