### ISSUE TITLE
Notification on "My" (always shown)

### ISSUE THREAD

**Issue by cvaconsulting** [elearningsoftware/moodle-mod_journal#32]
On "my" page (..../my/) there is always an indication that you have a journal/s that needs to be completed.

Info: Moodle 3.0.4 (Build: 20160616); mod_journal 30.1 (Build: 2015120401).

If you are a student, it doesn't matter if you have already answered and (or) already received feedback.

If you are a teacher, it doesn't matter if you have already given feedback.

Please indicate us if there is a roundabout about this issue and/or other ways of fixing this

Originally reported in: https://tracker.moodle.org/browse/CONTRIB-6594 (31/Oct/16)

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest release.
