### ISSUE TITLE
Add GDPR Support

### ISSUE THREAD

**Issue by TamaraGunkel** [elearningsoftware/moodle-mod_journal#36]
Hello,
it would be great if you could implement the new Privacy API. We are using the module and thus it is important for us that you implement it. Do you have already plans to add GDPR Support?
Thanks!

**Comment by adrian-sarmas** [comment]
We'll have a look at this in the following days. Thanks for reporting

**Comment by olive007** [comment]
Are you going to be implement the privacy provider soon ?

**Comment by danmarsden** [comment]
Are you going to maintain this plugin? - or do we need to find someone else to do it?

**Comment by adrian-sarmas** [comment]
I've implemented the privacy provider. Check the latest version.
