### ISSUE TITLE
Not compatible with 3.5

### ISSUE THREAD

**Issue by emmarichardson** [elearningsoftware/moodle-mod_journal#37]
After 3.5 upgrade, I had to disable Journal.  I found that it was throwing errors when running cron and effectively stopping cron from running.

**Comment by Jarvil** [comment]
Hello,

Will this plugin support Moodle 3.5? @adrian-sarmas

**Comment by Jarvil** [comment]
Hello,

Will this plugin support Moodle 3.5? @adrian-sarmas

**Comment by adrian-sarmas** [comment]
Now we have a new version that is compatible with Moodle 3.5
