### ISSUE TITLE
Save Each Instead of Save All?

### ISSUE THREAD

**Issue by dlove2** [elearningsoftware/moodle-mod_journal#38]
We love the Journal activity but have a suggestion.  Currently, teachers can grade and add feedback for the students but need to scroll to the bottom of the long list of entries to "Save all my feedback."  A connection interruption could cause many entries to be lost if the teacher grades and responds to a lot of entries before scrolling down to "save all." 
A "save" for each entry is a recommended improvement.

**Comment by adrian-sarmas** [comment]
This has been implemented in the latest version.
