### ISSUE TITLE
Latest 3.5 Stable breaks PHP Unit test env

### ISSUE THREAD

**Issue by pramithkm** [elearningsoftware/moodle-mod_journal#39]
Adopted your latest version "2018110700" for 3.5 Moodle. And when I ran the PHP Units I got following error. 

PHP Fatal error:  Interface 'core_privacy\local\request\core_userdata_provider' not found in /var/www/projects/streamvcs-moodle/mod/journal/classes/privacy/provider.php on line 43

There's no "core_userdata_provider" class on Moodle 3.5

**Comment by adrian-sarmas** [comment]
This should be fixed in the latest version
