### ISSUE TITLE
front page documentation error

### ISSUE THREAD

**Issue by pgee70** [elearningsoftware/moodle-mod_journal#43]
Isn't it funny how one missing command can make all the difference?
on the installation section there is:
git clone git://github.com/elearningsoftware/moodle-mod_journal.git mod/journal
git checkout MOODLE_XY_STABLE

the problem for me was that checkout MOODLE_36_STABLE is not my current branch - i use a different branch that stores our custom mods.  This subsequently let to what can be best called 'a series of unfortunate events'

you should probably have:
git submodule add -f https://github.com/elearningsoftware/moodle-mod_journal mod/journal
cd mod/journal
git checkout MOODLE_36_STABLE

**Comment by adrian-sarmas** [comment]
Thanks for the comment. Will add this to the docs
