### ISSUE TITLE
Missing return types for privacy methods

### ISSUE THREAD

**Issue by tobiasreischmann** [elearningsoftware/moodle-mod_journal#47]
Currently the two methods
`public static function get_metadata(collection $collection) : collection `
`public static function get_contexts_for_userid(int $userid) : contextlist`
do not specify the return types as above. Since at least in moodle 3.7 these return types are present at the parent class, this leads to a nasty error when deleting (and probably also exporting) user data. It is nasty, since the error is not really visible in the cron logs.

**Comment by sharpchi** [comment]
Also spotted this today as I was testing the privacy functionality. And yes it's messy when trying to export user data.

**Comment by sharpchi** [comment]
Ah I see what's happened. Support for PHP7 was dropped because the plugin wasn't working on an older version of moodle running on PHP5.x. #37 
I suspect it might be worth either splitting into branches for backward/forward compatibility or using the polyfil trait that some plugins are still using.

**Comment by izendegi** [comment]
I've recently seen that when processing a users' data export request in Moodle 3.7 it gets stuck in the journal module. 

I don't see any php errors but it seems like this issue is causing it, or am I wrong?

**Comment by sharpchi** [comment]
@izendegi if you apply Tobias' patch it will work again for you

**Comment by izendegi** [comment]
Yes, it worked, thank you!

**Comment by relecand** [comment]
Thank you for the patch. Works also with M3.5.

Would it be possible to accept the pull request: https://github.com/elearningsoftware/moodle-mod_journal/pull/48 ?

Could you please also patch it into the 3.5 branch?

Thank you!

Christian

**Comment by jpRsah** [comment]
Hello. The patch is still open?

Could you please add patch?

Thank you!

**Comment by mputzi** [comment]
**Please accept the pull request #48 !**
Today the cronjob on my site crashed because of this bug.
Thousands of E-Mails haven't been sent in time.

**Comment by agru** [comment]
I also tested this solution, it works great.

@adrian-sarmas - please accept the pull request #48 - this is urgent, as a cron job is dying silently if there is an accepted datarequest to delete the data of user(s). All other tasks of the cron job are then missing. For example there are no mails from forums sent! A lot of admins have problems with this, and it takes hours to find the bug and delete mod_journal or apply this patch manually.

**Comment by bozicm** [comment]
Our service was also bitten by this bug in the most critical period at the beginning of the reopening of schools. Here's [another case](https://moodle.org/mod/forum/discuss.php?d=409929) who got probably tripped by it. Please resolve this pull request as soon as possible!

**Comment by adrian-sarmas** [comment]
The fix has been merged. Thank you for the help

**Comment by bozicm** [comment]
Thank you!
