### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by jharej** [elearningsoftware/moodle-mod_journal#54]
Hi,

in last days I struggled with something not working in moodle and then discovered, that is this plugins fault. 

In ssl_error I got
[Thu Oct 17 14:54:17.177971 2019] [php7:error] [pid 29877] [client 109.182.0.233:56038] PHP Fatal error:  Declaration of mod_journal\\privacy\\provider::get_metadata(core_privacy\\local\\metadata\\collection $collection) must be compatible with core_privacy\\local\\metadata\\provider::get_metadata(core_privacy\\local\\metadata\\collection $collection): core_privacy\\local\\metadata\\collection in /........................../mod/journal/classes/privacy/provider.php on line 43
[Thu Oct 17 14:54:31.935460 2019] [php7:error] [pid 29560] [client 109.182.0.233:56048] PHP Fatal error:  Declaration of mod_journal\\privacy\\provider::get_metadata(core_privacy\\local\\metadata\\collection $collection) must be compatible with core_privacy\\local\\metadata\\provider::get_metadata(core_privacy\\local\\metadata\\collection $collection): core_privacy\\local\\metadata\\collection in /..................../mod/journal/classes/privacy/provider.php on line 43, referer: https://..................../admin/search.php

So I had to remove the plugin. I hope this helps.
bye

**Comment by agru** [comment]
I totally agree to this issue. When installed, and there is a privacy request by a user, the cron-job stops working, and for example no forum mails are sent, because the cron-job died. This is really a very annoying bug, as an administrator does not see the problem unless he/she notices where the cron-job is dying silently.

**Comment by adrian-sarmas** [comment]
This has already been fixed and is available in the master branch.
