### ISSUE TITLE
array_key_exists should only be used on arrays

### ISSUE THREAD

**Issue by sharpchi** [elearningsoftware/moodle-mod_journal#55]
In the lib.php file, a array_key_exists call is made on the $journal stdclass object. Since this is an object, it should be property_exists. This is throwing a deprecated message in the apache error logs.

PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/html/moodle38/mod/journal/lib.php on line 656

(I'm using PHP 7.4)

**Comment by adrian-sarmas** [comment]
Thank you @sharpchi . I've merged the pull request.
