### ISSUE TITLE
"Display description on course page" check box

### ISSUE THREAD

**Issue by ottorabo** [elearningsoftware/moodle-mod_journal#57]
Hello,
i want to ask you, if you can add an option to display the journal's despriction on course page?

Best Regards
Ralf

**Comment by glimatecnologia** [comment]
Sim

Em sex., 29 de mai. de 2020 às 07:45, ottorabo <notifications@github.com>
escreveu:

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest release.
