### ISSUE TITLE
Saving feedback is updating all students grades

### ISSUE THREAD

**Issue by crystalvaughn** [elearningsoftware/moodle-mod_journal#61]
When a journal has multiple entries made by students. If a teacher grades one student journal it updates the other students grades to 0 in the gradebook. Previously the teacher was able to grade one student and saving the feed back would only update the one student.  

Steps to recreate:

1. Log on a Moodle course
2. Create a journal activity
3. Log in as student1 and enter a journal entry.  
4. Log in as student2 and enter a journal entry.
5. Log in as student3 and enter a journal entry. 
6. Log in as the teacher in the course and view the journal entries. 
7.  Add feedback and a score to student1's journal entry. 
8. Click the submit all feedback.
9. All the students feedback and grades are updated.

**Comment by will-bulluck** [comment]
I have a client experiencing the same issue on MOODLE_35

**Comment by will-bulluck** [comment]
Any update on this?

**Comment by larsbonczek** [comment]
We have encountered this issue in Moodle 3.9. The solution suggested by amandadoughty works for us. Could it please be merged?

**Comment by will-bulluck** [comment]
Any updates to this?

**Comment by will-bulluck** [comment]
Any Update on this?

**Comment by adrian-sarmas** [comment]
I've merged the pull request. Thanks for helping!
