### ISSUE TITLE
New release for 20200911 contains old version file causing upgrade to fail

### ISSUE THREAD

**Issue by drachels** [elearningsoftware/moodle-mod_journal#62]
The release from yesterday, 20200911, contains the old version of the version.php file which causes the upgrade to fail.

**Comment by katcher** [comment]
has the file been updated?

**Comment by drachels** [comment]
NO! It has NOT be updated.

**Comment by fnfao** [comment]
Can the code be updated to resolve the issue or should I wait for a patch?

**Comment by kalisp** [comment]
It is not just version.php, whole codebase for latest build is old, imho.

**Comment by adrian-sarmas** [comment]
I've made some fixes and should be ok now.

**Comment by kalisp** [comment]
Seems fixed. Thanks.

**Comment by fnfao** [comment]
Worked for me too. Thank you.
