### ISSUE TITLE
Privacy provider export_user_data leads to an error

### ISSUE THREAD

**Issue by adpe** [elearningsoftware/moodle-mod_journal#64]
Hi @adrian-sarmas 

It's the first time we are using the export functionality in Moodle, but we got this error:

```php
<webroot>/lib/modinfolib.php(2237): moodle_database->get_record_sql()
<webroot>/mod/journal/classes/privacy/provider.php(167): get_course_and_cm_from_cmid()
<webroot>/lib/moodlelib.php(8083): mod_journal\privacy\provider::export_user_data()
<webroot>/privacy/classes/manager.php(578): component_class_callback()
<webroot>/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
<webroot>/privacy/classes/manager.php(339): core_privacy\manager->handled_component_class_callback()
<webroot>/admin/tool/dataprivacy/classes/task/process_data_request_task.php(114): core_privacy\manager->export_user_data()
<webroot>/lib/cronlib.php(333): tool_dataprivacy\task\process_data_request_task->execute()
<webroot>/lib/cronlib.php(198): cron_run_inner_adhoc_task()
<webroot>/lib/cronlib.php(76): cron_run_adhoc_tasks()
<webroot>/admin/cli/cron.php(79): cron_run()
```

We're using Moodle 3.9.2 (Build: 20200914) and mod_journal version 2.1.0 (Build: 2020091100).

HTH,
Adrian

**Comment by gemguardian** [comment]
We received the samen messages on  Moodle 3.9.2 (Build: 20200914) and mod_journal version 2.1.0 (Build: 2020091100).

#0 <webroot>/lib/modinfolib.php(2237): moodle_database->get_record_sql('\n              ...', Array, 2)
#1 <webroot>/mod/journal/classes/privacy/provider.php(167): get_course_and_cm_from_cmid(NULL, 'journal')
#2 <webroot>/lib/moodlelib.php(8076): mod_journal\privacy\provider::export_user_data(Object(core_privacy\local\request\approved_contextlist))
#3 <webroot>/privacy/classes/manager.php(578): component_class_callback('mod_journal\\pri...', 'export_user_dat...', Array)
#4 <webroot>/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback('mod_journal', 'core_privacy\\lo...', 'export_user_dat...', Array)
#5 <webroot>/privacy/classes/manager.php(339): core_privacy\manager->handled_component_class_callback('mod_journal', 'core_privacy\\lo...', 'export_user_dat...', Array)
#6 <webroot>/admin/tool/dataprivacy/classes/task/process_data_request_task.php(114): core_privacy\manager->export_user_data(Object(core_privacy\local\request\contextlist_collection))
#7 <webroot>/lib/cronlib.php(333): tool_dataprivacy\task\process_data_request_task->execute()
#8 <webroot>/lib/cronlib.php(198): cron_run_inner_adhoc_task(Object(tool_dataprivacy\task\process_data_request_task))
#9 <webroot>/lib/cronlib.php(76): cron_run_adhoc_tasks(1604562370)
#10 <webroot>/admin/cli/cron.php(79): cron_run()
#11 {main}

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest release.
