### ISSUE TITLE
Error with double quotes on PostgreSQL

### ISSUE THREAD

**Issue by izendegi** [elearningsoftware/moodle-mod_journal#78]
I've read this message from Hiroto Kagotani on the [plugin database comments](https://moodle.org/plugins/mod_journal)

    Hi, thank you very much for this very useful plugin.
    Version 2022083000 does not work with PostgreSQL since 'journal' has been quoted by "(double quotes)" in lib.php.
    Workaround is replacing " with '.
    Thanks again.

and I bring that here just in case you missed it: #77

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest update on master branch.
