### ISSUE TITLE
Module purpose and Icon

### ISSUE THREAD

**Issue by tkorner** [elearningsoftware/moodle-mod_journal#82]
Thanks a lot for your great plugin and your work.
We are currently working on the update to 4.0. We've realized that you recently updated the plugin and the icon. 
The icon's line are a bit smaller than the standard icons. It would be awesome if you could increase the line thickness just a bit.
![Bildschirmfoto 2022-09-15 um 09 49 53](https://user-images.githubusercontent.com/3245718/190371173-025a4993-56f5-45d8-bfb2-0e1774b7a78e.jpg)
if you compare it to this one (standard resource file)

![Bildschirmfoto 2022-09-15 um 09 52 41](https://user-images.githubusercontent.com/3245718/190371483-cbbf5e48-aebb-4bf4-b65e-571ee43a386d.jpg)

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest version on the master branch.
