### ISSUE TITLE
"No grade..." option doesn't work when saving a single feedback

### ISSUE THREAD

**Issue by jmatikainen** [elearningsoftware/moodle-mod_journal#85]
Saving a single feedback forces 0/failed grade for the student if a teacher gives feedback with "No grade..." option selected. This is not visible for the teacher unless the page is refreshed.

However, "Save all my feedback" button retains the "No grade..." option in the feedback.

Moodle version 3.11.10 and Journal is the latest 4.0.1 (Build: 2022091600).

**Comment by adrian-sarmas** [comment]
This has been fixed in the latest version on github (the master branch). I'll add it on moodle.org in a couple of days.
