### ISSUE TITLE
Sort descending and ascending does not work

### ISSUE THREAD

**Issue by kiratskitizing** [elearningsoftware/moodle-mod_journal#97]
It appears that Sort Ascending and Sort Descending does not work

Replication:
1. Create a course. Enrol 3 students.
2. Turn edit mode to On.
3. Add mod_journal and set:
Name: myJournal
Journal question: What is the best thing that happened today?
Days available: Always open
4. Log in as the first student and Start/edit journal entry
5. Wait for one minute, log in as second student and start/edit journal entry
6. Wait for one minute, log in as third student and start/edit journal entry
7. As admin/teacher, visit the journal activity.Click "View 3 journal entries".
8. Note the current sort is Date Ascending, the following is displayed:
3rd student Last edited: Wednesday, 19 July 2023, 1:20 PM
2nd student Last edited: Wednesday, 19 July 2023, 1:19 PM
1st student Last edited: Wednesday, 19 July 2023, 1:18 PM
9. Change Date Ascending to Date Descending, the following is displayed
3rd student Last edited: Wednesday, 19 July 2023, 1:20 PM
2nd student Last edited: Wednesday, 19 July 2023, 1:19 PM
1st student Last edited: Wednesday, 19 July 2023, 1:18 PM
10. Change Date Descending to Date Ascending, the following is displayed
3rd student Last edited: Wednesday, 19 July 2023, 1:20 PM
2nd student Last edited: Wednesday, 19 July 2023, 1:19 PM
1st student Last edited: Wednesday, 19 July 2023, 1:18 PM

RESULT as seen in steps 8,9,10, the results do not change.

**Comment by adrian-sarmas** [comment]
I fixed this issue in the latest version on github. @kiratskitizing thank you for reporting.
