### ISSUE TITLE
Error when exporting all of a users data

### ISSUE THREAD

**Issue by davefoord** [elearningsoftware/moodle-mod_journal#99]
I have a user that has requested to have an export of all their data, which I am running, but I have received an email notification saying that there is an issue with the Journal plugin, giving this information:

Class "entry" not found

#0 /var/www/moodle/lib/moodlelib.php(8144): mod_journal\privacy\provider::export_user_data()
#1 /var/www/moodle/privacy/classes/manager.php(578): component_class_callback()
#2 /var/www/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#3 /var/www/moodle/privacy/classes/manager.php(339): core_privacy\manager->handled_component_class_callback()
#4 /var/www/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(114): core_privacy\manager->export_user_data()
#5 /var/www/moodle/lib/cronlib.php(367): tool_dataprivacy\task\process_data_request_task->execute()
#6 /var/www/moodle/lib/cronlib.php(198): cron_run_inner_adhoc_task()
#7 /var/www/moodle/lib/cronlib.php(76): cron_run_adhoc_tasks()
#8 /var/www/moodle/admin/cli/cron.php(178): cron_run()
#9 {main}

**Comment by adrian-sarmas** [comment]
@davefoord Which Moodle version are you using?

**Comment by davefoord** [comment]
@adrian-sarmas We are using 4.1.4+ (Build: 20230623)

Thanks

**Comment by adrian-sarmas** [comment]
@davefoord I've fixed this issue in the latest version on github.com (2023091500)
I'll soon add this fix to the moodle.org section for this plugin.
